# Needed Travis Variables
# DEPLOY_USER, DEPLOY_PASS, DEPLOY_HOST

# No sudo
sudo: false
# install node on the newest version of 4
language: node_js
node_js:
    - '4'
 # Npm install bower and grunt, then bower install and npm install
before_script:
    - 'gem install sass --version "=3.4.22"'
    - 'gem install compass --version "=1.0.3"'
    - 'npm install -g bower grunt-cli'
    - 'npm install'
    - 'bower install'

# Simply build the project for testing for now
script:
    - 'grunt'

# Deploymentt will go here, going to use: https://neemzy.org/articles/deploy-to-your-own-server-through-ssh-with-travis-ci
addons:
  apt:
    packages:
    - sshpass
after_success:
    - if [ "$TRAVIS_BRANCH" == "installTravis" ]; then echo "Deploying the project since we are on master branch...";
        export SSHPASS=$DEPLOY_PASS;
        echo "Branch we are currently testing from:";
        echo $TRAVIS_BRANCH;
        echo "Current Directory and it's contents:";
        pwd;
        ls;
        echo "Packaging built project";
        mkdir build;
        mv * build;
        tar -czf package.tgz build;
        echo "Current Directory and it's contents:";
        pwd;
        ls;
        sshpass -e scp -o StrictHostKeyChecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:/home/$DEPLOY_USER;
        cat deploy.sh | sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "cat > /tmp/deploy.sh;
        chmod 755 /tmp/deploy.sh;
        /tmp/deploy.sh";
    fi
